# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  setup:
    name: Set up env
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Cache setup
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ runner.os }}-${{ github.ref }}-${{ github.sha }}-setup

  linting:
    name: Verify linting
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ runner.os }}-${{ github.ref }}-${{ github.sha }}-setup
      
      - name: Lint
        run: yarn lint-only --max-warnings=0
  
  build:
    name: Build vue-leaflet
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ runner.os }}-${{ github.ref }}-${{ github.sha }}-setup

      - name: yarn build
        run: yarn build

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ runner.os }}-${{ github.ref }}-${{ github.sha }}-build

  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ runner.os }}-${{ github.ref }}-${{ github.sha }}-build
      
      - name: Run tests
        run: yarn test

  publish:
    name: Publish if applicable
    runs-on: ubuntu-latest
    if: github.repository_owner == '@vue-leaflet'
    needs: 
      - unit_tests
      - linting
    steps:
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
